### ISSUE TITLE
Can't Identify Nefarious Virtual Gamepad Emulation Bus Driver

### ISSUE THREAD

**Issue by 0Zo0m0** [ViGEm/ViGEmBus#104]
My Can't Identify This Diver I Don't Know Why .
Can You Pls Fix This .

![Screenshot (3)](https://user-images.githubusercontent.com/83219692/117543648-25468300-b037-11eb-9311-e94816f561ce.png)

**Comment by nefarius** [comment]
[Closed as off-topic](https://vigem.org/Community-Support/).
