### ISSUE TITLE
the driver have a weird issue with me

### ISSUE THREAD

**Issue by nefaruisuser** [ViGEm/ViGEmBus#107]
![16230235438636588648117433120521](https://user-images.githubusercontent.com/85463866/120944123-ae320680-c72a-11eb-9d0d-8786445abc85.jpg)
there is this mark on the driver from the device manager and i cant use the wooting double mouvement plz help

**Comment by nefarius** [comment]
This is not a helpdesk, read and respect the clearly outlined resources to use to seek help.
