### ISSUE TITLE
Isn't working with Tetr.io (Web Based Tetris Clone with a Downloadable Client)

### ISSUE THREAD

**Issue by dude98** [ViGEm/ViGEmBus#110]
**Describe the bug**
Trying to configure the device in the options menu doesn't let you bind anything

**To Reproduce**
Steps to reproduce the behavior (example):
1. Start vigem with any controller configured already
2. open tetr.io
3. go to the options menu, controls, and set it to custom
4. Try to bind anything to your controller

**Expected behavior**
I should be able to bind the buttons and navigate the game without my mouse.

**Screenshots**

**System details (please complete the following information):**
 - OS: Win 10
 - Feeder software: USendMii (Wii U), 3DSCPlusViGEM (3DS/ 3DS XL), Probably Happens with any other one too.
 - Driver Version: 1.17.333

**Additional context**
Doesn't work on the web browser verisons of tetr.io either, or firefox for that matter.

**Comment by nefarius** [comment]
Does the emulated controller work with [this](https://github.com/nefarius/ScpToolkit/raw/master/SCPUser.exe) or [this](https://gamepad-tester.com/)?

What is emulated; x360 pad or ds4?
