### ISSUE TITLE
I HATE VIGEMBUS!!

### ISSUE THREAD

**Issue by PoggersPlayer** [ViGEm/ViGEmBus#120]
I cannot take bullshit anymore. ViGEmBus Breaked the rules when i Install this. It found Full Disk Space Error, when the people didn't have full Disk Space. That's why ViGEmBus didn't listen to rules.

**Comment by Masamune3210** [comment]
That's not how that works at all

**Comment by nefarius** [comment]
What did I just read 😆 Who let kids on GitHub.
