### ISSUE TITLE
Setup Wizard ended prematurely : setupapi file marks error 0xe0000223

### ISSUE THREAD

**Issue by BlueLight-yt** [ViGEm/ViGEmBus#125]
I have an error, when I try to install Vigem, because before I had it on another pc and if it worked, this one gives me an error
![ERROR VIRTUAL 2](https://user-images.githubusercontent.com/88950010/129639120-c4f35793-ac5d-49b2-96d8-634462e4a781.png)
![ERROR VIRTUAL](https://user-images.githubusercontent.com/88950010/129639121-0d29d96e-51cb-42f1-80fe-758a8293b1f8.png)
![error](https://user-images.githubusercontent.com/88950010/129639123-8989ce55-13a1-41cc-b075-1d1d0cc3e5a8.png)

**Comment by Masamune3210** [comment]
Why do people insist on not reading logs that explain the issue, ignore the issue templates, and then expect help....

**Comment by nefarius** [comment]
Nice, sure, add screenshots of text so it's extra hard to read or copy. Sometimes I really worry about the world...

Read 👏 And 👏 Follow 👏 The 👏 Templates 👏 And 👏 Get 👏 Out 👏 Of 👏 The 👏 Issue 👏 Tracker 👏
