### ISSUE TITLE
DualSense rumble doesn't work with DualShock4 Emulation

### ISSUE THREAD

**Issue by Clickrouc** [ViGEm/ViGEmBus#129]
Hello! I bought DualSense to play on PC. Many newer games support DS4 and so I would like to use this emulation mode (this is necessary to support correct button prompts). But with this emulation mode, rumble does not work. At the same time, everything works well in the XBox360 emulation mode. I tested this in DS4Windows and DualSenseX.

Sorry for my English, I'm not a native speaker.

**Comment by nefarius** [comment]
That's a known DS4Windows issue I can't do anything about at this point in time.
