### ISSUE TITLE
Uninstalling Auto-reboots the PC

### ISSUE THREAD

**Issue by Paliverse** [ViGEm/ViGEmBus#132]
Direct source to the faulty line:
https://github.com/ViGEm/ViGEmBus/blob/a9e7d6b38be921aac5decefd52181742b7507d42/setup/Product.wxs#L96

![image](https://user-images.githubusercontent.com/4289084/174494025-e01f1f40-f34c-455d-bd8e-9fc96374f9ac.png)

**Comment by nefarius** [comment]
Fixed in latest pre-release.
