### ISSUE TITLE
Update was erroniously offered to Windows 7 users

### ISSUE THREAD

**Issue by Squall-Leonhart** [ViGEm/ViGEmBus#137]
~~https://discord.vigem.org/ is no longer working.~~

Also, the vigem updater notified windows 7 users of an update

![image](https://user-images.githubusercontent.com/1098176/175891697-8d617817-5ea5-450f-ab0e-149ccbdf97b1.png)

**Comment by Squall-Leonhart** [comment]
hold up, it worked when clicking but not when entering the link into discord directly

**Comment by nefarius** [comment]
Oops. Disabled it until I find a better solution. Thanks for reporting!

**Comment by nefarius** [comment]
Using new URL exclusively for the Windows 10/11 builds and leaving Windows 7 alone 😇
