### ISSUE TITLE
Rename some GUIDs

### ISSUE THREAD

**Issue by DJm00n** [ViGEm/ViGEmBus#14]
GUID_PNP_LOCATION_INTERFACE
https://github.com/ViGEm/ViGEmBus/blob/1fdab3e8f9ecdb6689d6351dadd91e4629a12418/sys/Xusb.h#L29
https://github.com/ViGEm/ViGEmBus/blob/1fdab3e8f9ecdb6689d6351dadd91e4629a12418/sys/Xgip.h#L27

GUID_D3COLD_SUPPORT_INTERFACE
https://github.com/ViGEm/ViGEmBus/blob/1fdab3e8f9ecdb6689d6351dadd91e4629a12418/sys/Xusb.h#L33
https://github.com/ViGEm/ViGEmBus/blob/1fdab3e8f9ecdb6689d6351dadd91e4629a12418/sys/Xgip.h#L31

GUID_REENUMERATE_SELF_INTERFACE_STANDARD
https://github.com/ViGEm/ViGEmBus/blob/1fdab3e8f9ecdb6689d6351dadd91e4629a12418/sys/Xusb.h#L37
https://github.com/ViGEm/ViGEmBus/blob/1fdab3e8f9ecdb6689d6351dadd91e4629a12418/sys/Xgip.h#L35

GUID_POWER_THREAD_INTERFACE
https://github.com/ViGEm/ViGEmBus/blob/1fdab3e8f9ecdb6689d6351dadd91e4629a12418/sys/Xgip.h#L39

**Comment by nefarius** [comment]
Very nice, thank you!
