### ISSUE TITLE
emulated controller not listed by usbview(usbTreeView) and usbTrace

### ISSUE THREAD

**Issue by walkongit** [ViGEm/ViGEmBus#15]
This emulated usb controller is not listed when I use some usb tool, eg.
usbTreeView: www.uwe-sieber.de
usbTrace: http://sysnucleus.com/
It is nice If ViGemBus be recognized by them.
plus. If ViGem could be listed by vmware workstation or virtualbox. Then we could redirect emulated controller to vmware guest os(android, linux, macos...)

**Comment by nefarius** [comment]
Good idea. Will probably need to implement a few other interfaces to make it represent itself as a "true" USB bus device.

**Comment by atmgnd** [comment]
checkout https://sourceforge.net/p/usb-vhci/virtusb/ci/master/tree/

**Comment by nefarius** [comment]
Progress 😎 

![image](https://user-images.githubusercontent.com/286631/82728583-7d368d80-9cf1-11ea-8fa9-e67996d85f8d.png)

**Comment by atmgnd** [comment]
Great. very nice work, can't wait to try.
Also can we make ViGEmBus a generic purpose emulated usb bus, like Microsoft USB Device Emulation(UDE)(I nerver used UDE, i dont like it). some like below:
├── Vuirtual Usb Bus (kernel mode)
│   └── Emulated Xbox Controller(Normal win32 exe)
│   └── Emulated Usb keyboard(Normal win32 exe)
│   └── Emulated Usb camera(Normal win32 exe)
│   └── Emulated xxx(Normal win32 exe)

here is another virtual usb bus (a leak comercial software) I found, I have checked that it is working.
https://github.com/seanxs/ung_sean

**Comment by nefarius** [comment]
@atmgnd sorry I somehow missed that replay; I have exactly that in the pipeline, stay tuned 😄

**Comment by nefarius** [comment]
Progress 😎 

![image](https://user-images.githubusercontent.com/286631/91030814-0666a480-e600-11ea-9d5d-b0e8fd16817a.png)

**Comment by nefarius** [comment]
This is a topic for the successor.
