### ISSUE TITLE
Installer issued restart command without any prompt

### ISSUE THREAD

**Issue by St0RM53** [ViGEm/ViGEmBus#151]
Self-explanatory, v1.18.367.0

Really annoying behavior, i haven't re-encountered in like 10 years..please configure installer not to this.

**Comment by nefarius** [comment]
The installer is configured to give you a prompt, so IDK what I could possibly change there.

**Comment by ubergeek77** [comment]
@nefarius Is it possible for you to test this behavior? I was given no warning for a restart when installing ViGEmBus.

**Comment by nefarius** [comment]
Yep, that is a bug in the installer, need to check if we fixed that already in the sources...

**Comment by nefarius** [comment]
Nope, it has been fixed quite a while ago.
