### ISSUE TITLE
[Enhancement] Remove the Windows Server restrictions from the ViGEmBus installer

### ISSUE THREAD

**Issue by akemin-dayo** [ViGEm/ViGEmBus#153]
The ViGEmBus 1.21.442 installer explicitly blocks installation on all Windows Server OSes, presumably due to the fact that the XInput controller drivers are not installed by default on Windows Server.

> ViGEm Bus Driver can not be installed on the following Windows versions: Windows Vista x64, Windows Server 2008 x64, Windows 7 x64, Windows Server 2008 R2 x64, Windows 8 x64, Windows Server 2012 x64, Windows 8.1 x64, Windows Server 2012 R2 x64, Windows Server x64.

This restrictions prevents users from using newer versions of the ViGEmBus installer on systems that already have XInput controller drivers installed. Some users may also only plan on instantiating emulated DS4 devices, which do not require XInput drivers to begin with.

It would be nice if these restrictions were removed (as was the case in previous ViGEmBus installers), so the somewhat-hacky workaround found below would no longer be required in order to install newer ViGEmBus versions on Windows Server.

For reference, this is occurring on Windows Server 2022 20348.1070 21H2.

## Workaround for installing ViGEmBus >= 1.21.442 on Windows Server
1. Extract the ViGEmBus installer EXE by running `./ViGEmBus_1.21.442_x64_x86_arm64.exe /extract vigembus`.
2. Inside the extracted folder (which may end up being a random string like `5215C05`), right click on `ViGEmBus.inf` and click "Install".
	* **※ NOTE:** If your system architecture is _not_ x86_64, look inside the "32-bit" or "ARM64" folders instead.
3. Reboot your system.
4. Verify that the new version of "Nefarius Virtual Gamepad Emulation Bus" appears in Device Manager, under "System Devices".

**Comment by nefarius** [comment]
I will not remove that restriction because I made the setup for individuals, gamers on their home machine running a client OS, not people who use it on cloud machines or in Enterprise setups without ever contributing anything back to the project 🙂

**Comment by nefarius** [comment]
> Ah, so it's intended behaviour. Well, that's fair.

Yes, I'm afraid you suffer the consequences from past abuse of my craft, sorry for the inconveniences but I'll stick to my principles.

**Comment by akemin-dayo** [comment]
Mnn, sorry to hear about that :/

In any case, it's just a minor inconvenience anyway (though I am… a developer, so not exactly a typical user ;P)

I _do_ mainly use ViGEmBus (+ DS4Windows) on my local Windows 10 machine, I just also happen to have a Google GCE VM that I play around with occasionally since I was given some free credits that have an expiration date ;P

No worries though, it's your project. Really happy to see the new features recently!

**Comment by Anopetia** [comment]
@akemin-dayo  Thank you so much for this help! Life saver :)

**Comment by Astrian** [comment]
Thanks, @akemin-dayo, and I understand and appreciate the work by @nefarius. However, is it necessary that put a tip inside the installer to explain this? I was struggling with this problem for two days 😂

**Comment by nefarius** [comment]
I updated the README accordingly. The installer is a 3rd party product, not sure it that is possible, I'll put it on the pile of things to eventually look into 😛

**Comment by Nanorulez123** [comment]
Some home users use server 2022 for the higher uptime ect for 24/7 usage as a game server, most corps would use linux anyway

**Comment by Masamune3210** [comment]
Not gonna happen. Not sure why you thought commenting on another issue after being told no in the one you made would end any better

**Comment by Masamune3210** [comment]
As for the argument about uptime, this is my computer running Windows 11 Pro
![image](https://user-images.githubusercontent.com/1053504/228399806-bdc47360-44aa-4b9f-bc38-18c846cce39a.png)


No hibernate, no reboot, no sleep. You don't need server to have long stable uptimes, you need a not broken to pieces install
