### ISSUE TITLE
DualSense Support?

### ISSUE THREAD

**Issue by anar4732** [ViGEm/ViGEmBus#163]

**Comment by Masamune3210** [comment]
The library isnt involved with this. All it does is take input from one thing and convert it to another thing, its up to the system or a tool like DS4Windows to handle getting things connected if needed and using the library to do whatever it wants to do with the data

**Comment by nefarius** [comment]
> The library isnt involved with this. All it does is take input from one thing and convert it to another thing, its up to the system or a tool like DS4Windows to handle getting things connected if needed and using the library to do whatever it wants to do with the data

I think OP is asking about DualSense **emulation** support which is a valid question and on the todo for quite some time.

**Comment by nefarius** [comment]
Closing, see #139
