### ISSUE TITLE
VirsuTotal Detection

### ISSUE THREAD

**Issue by BeratTezer** [ViGEm/ViGEmBus#168]
VirusTotal shows this cautions. Is it normal?

![image](https://user-images.githubusercontent.com/64587561/219339120-f7a506c2-3895-4219-9ee8-38b3fcede4db.png)

**Comment by nefarius** [comment]
Couple hundred thousand of installations tend to disagree, called a "false positive".

**Comment by BeratTezer** [comment]
I'm just a nervous person, I hope it wasn't disturbing. Thanks for your response.

**Comment by nefarius** [comment]
I'm not easy to disturb 😜
