### ISSUE TITLE
Wireless Controller - Driver Error

### ISSUE THREAD

**Issue by pokeygithub** [ViGEm/ViGEmBus#24]
Feeder Software is DS4Win

**Comment by pokeygithub** [comment]
Windows 10 Version 1903 fully patched.  PS4 Controller shows that it is connected, then a few seconds later it shows Driver error.  Click PS4 controller connects again.  few seconds later Driver error.  This is with version 1.16.115.

**Comment by pokeygithub** [comment]
It does work correctly when plugged in via USB, Bluetooth is what is failing for me.

**Comment by nefarius** [comment]
Could you provide some screenshots of the areas where said error occurs? Because from the description alone I don't quite get what the issue is about, thanks!

**Comment by pokeygithub** [comment]
I am so sorry! I forgot to update this ticket.  Ended up the brand new USB to BT/Wifi Adapter just quit sending BT.  Replaced it with a new Killer BT/Wifi adapter and has been working perfectly ever since!  I really appreciate everything you have done with this driver as using PS4 controllers on my PC is an absolute dream!  Once again thank you for your hard work and willingness to help this dumb old guy.
