### ISSUE TITLE
ViGEm Updates Has Expired SSL Certificate

### ISSUE THREAD

**Issue by quinn-brittain** [ViGEm/ViGEmBus#28]
The certificate expired on the 10th and hasn't been updated.
I noticed this because I am now getting a warning window on Windows10.
![ViGEm-updates-SSLcert-expired-1](https://user-images.githubusercontent.com/44992697/72212225-2056db00-34a6-11ea-8cfe-8f857981bedf.png)
![ViGEm-updates-SSLcert-expired-2](https://user-images.githubusercontent.com/44992697/72212228-277de900-34a6-11ea-9d40-17774ae22c27.png)
![ViGEm-updates-SSLcert-expired-3](https://user-images.githubusercontent.com/44992697/72212229-28af1600-34a6-11ea-9e47-04ccc93290af.png)

**Comment by nefarius** [comment]
Never have I received the same message on so many different channels 😅 and ofc. this had to happen the one time I'm traveling without PC/Laptop... Will fix ASAP 😜

**Comment by nefarius** [comment]
Fixed 😎
