### ISSUE TITLE
Emulated DS4 controller is not seen by PSNow

### ISSUE THREAD

**Issue by KizzyCode** [ViGEm/ViGEmBus#29]
**Describe the bug**
If I emulate a DS4 controller using VDX, it is not detected by PSNow. If I change the type to XBox 360 and reconnect, the controller is detected immediately and if I change it back to DS4, it is not seen anymore. I've also tried it with UCR, but no difference.

**To Reproduce**
Steps to reproduce the behavior (example):
1. Start program VDX via Steam (for Steam controller support)
2. Change the controller type in VDX to DS4 and click connect
3. Start PSNow
4. No controller available
5. Try various reconnects as DS4
6. Still no controller avaliable

**Expected behavior**
I'd expect that PSNow detects the virtual DS4 controller

**System details (please complete the following information):**
 - OS: Windows 10 Pro 10.0.18363 Build 18363
 - Feeder software: VDX, UCR
 - Driver Version: 1.16.116

**Comment by nefarius** [comment]
The way the DS4 has been emulated hasn't changed and Steam does all sorts of hookery that could interfere plus it's been reported countless times that it works with PSNow but I can't verify myself due to lack of equipment.
