### ISSUE TITLE
Installer "Invalied drive Z:"

### ISSUE THREAD

**Issue by lividus** [ViGEm/ViGEmBus#36]
**Describe the bug**
Installer (1.16.116) show warninng window "Invalied drive Z:" and installation is interrupted

To Reproduce
Just start installer and click install

System:
 - OS: 10 1806
 - Driver Version: 1.16.116

**Additional context**
Drive Z: is webdav

**Comment by nefarius** [comment]
You can not run an elevated application from a network drive, that's a Windows limitation, nothing I can help you with.

**Comment by lividus** [comment]
> 
> 
> You can not run an elevated application from a network drive, that's a Windows limitation, nothing I can help you with.

The network drive is simply present in the system. Z: not use for start installer or install to them. If i disable all network drives installer work as expeted.

**Comment by nefarius** [comment]
That's quite an important detail 😆

**Comment by nefarius** [comment]
Can't reproduce on v1.17.333
