### ISSUE TITLE
Wrong version of the installer on the main page

### ISSUE THREAD

**Issue by MagicOneFr** [ViGEm/ViGEmBus#41]
**Describe the bug**
The link to the latest version on the main page is wrong.

**To Reproduce**
1. Go to https://github.com/ViGEm/ViGEmBus
2. Click on https://github.com/ViGEm/ViGEmBus/releases/latest in the installation chapter
3. The version 1.16.115 is displayed instead of 1.16.116

**Expected behavior**
Display the good version of the installer.

**System details (please complete the following information):**
 - Any OS and web browser

**Comment by nefarius** [comment]
Indeed! Wonder how that happened, I fixed it by marking it as a pre-release and un-marking again, thanks for reporting!
