### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by At1a** [ViGEm/ViGEmBus#42]
sorry im really new and i need this for some joy-con software and im not sure how to install it

**Comment by webtroter** [comment]
No pro here, but have you read ?
Here : https://github.com/sam0x17/XJoy

All the instructions are there. And I don't have joycons.

**Comment by nefarius** [comment]
@At1a the README clearly links to the download location of the setup. Once again, the issue tracker is about reporting **issues**, not support.

@webtroter the linked project has a misleading/useless link to ViGEm in the README, that should be rectified by the author or a PR.
