### ISSUE TITLE
Install fails with fatal error and rollbacks

### ISSUE THREAD

**Issue by chris-day** [ViGEm/ViGEmBus#43]
ViGEmBus_Setup_1.16.116 - Installation reports a fatal error and rollback on Windows 10 build Microsoft Windows NT 10.0.18363.0

Logfile attached for your perusal.

[MSI5f10e.LOG](https://github.com/ViGEm/ViGEmBus/files/4589867/MSI5f10e.LOG)

**Comment by nefarius** [comment]
Can't reproduce on v1.17.333
