### ISSUE TITLE
How to safely uninstall Fireshock by ViGEm ?

### ISSUE THREAD

**Issue by 0lm** [ViGEm/ViGEmBus#48]
Hi there. Can someone tell me how I completely uninstall Fireshock?
I basically would like to revert my system back to the time before I installed Fireshock. And no I dont have a System backup. i uninstalled in my Programs already, but there are traces.
for example, i have this folder left: Windows\System32\drivers\UMDF
do i need to completele delete this folder? or is only the fireshock.ddl related to fireshock instead of the whole folder? 

I would like to know a safe method to delete all traces of firechock.

EDIT : it is the same with vigembus. i uninstalled it, but there are still a few traces. like this folder here Windows\System32\DriverStore\FileRepository\vigembus.inf_amd64_dc012c700833063e
(i already used sc delete vigembus and deleted vigembus.sys)
can i delete safely the stated folder without anny worries?

**Comment by nefarius** [comment]
1) Not a helpdesk, there's literally links to the right places scattered all around
2) Don't mess with Windows directories or you'll get bitten, use the proper tools like [DriverStore Explorer](https://github.com/lostindark/DriverStoreExplorer/releases)

**Comment by 0lm** [comment]
I found these tutorials and I did what it was stated in them. BUt still, there were leftovers and there were no information about these leftovers. Thats why I asked if it is safe to deleted the stated folders/files.

**Comment by nefarius** [comment]
I see, DSE will be your friend there, it uses safe Windows routines to get the job done.
