### ISSUE TITLE
Stops mid-installation, then rolls back changes.

### ISSUE THREAD

**Issue by ScottQB4** [ViGEm/ViGEmBus#49]
Tried disconnecting the controller, uninstalling the driver (first try was an update attempt) as well as DS4Windows. Running Win10.
![11](https://user-images.githubusercontent.com/15930271/86198265-3411fe80-bb25-11ea-8c5a-f2db687e4da5.png)

**Comment by nefarius** [comment]
[Please follow this](https://forums.vigem.org/topic/290/troubleshooting-a-failed-vigem-bus-setup)

**Comment by nefarius** [comment]
Can't reproduce on v1.17.333
