### ISSUE TITLE
Setup crashes when encountering a substitute drive

### ISSUE THREAD

**Issue by Lunatoid** [ViGEm/ViGEmBus#52]
**Describe the bug**
Setup fails to install if there any any substitute/virtual drives with the message: `Invalid Drive: X:\`
I guess this isn't a bug with the driver itself but more of the setup, but I couldn't find a repository for that.

**To Reproduce**
1. Create a substitute drive, e.g. `subst X: C:\SomeFolder`
2. Run the setup
3. See the error message box appear when the status "Computing space requirements" is shown

**Expected behavior**
The setup shouldn't crash when trying to compute space requirements for substituted drives

**Screenshots**
![ViGEmBus_Setup_1 16 116_dXUgQtU0bV](https://user-images.githubusercontent.com/13891859/90987682-214c0100-e58d-11ea-935a-b6b08985035b.png)

**System details (please complete the following information):**
 - OS: Windows 10 Pro (18363)
 - Driver Version: 1.16.116

**Workaround**
A simple workaround is simply to delete the substituted drive with e.g. `subst /D X:` but this is undesirable.

**Comment by nefarius** [comment]
Can't reproduce on v1.17.333
