### ISSUE TITLE
Hacked PS2 running as a controller over the network

### ISSUE THREAD

**Issue by jmoseman01** [ViGEm/ViGEmBus#57]
**Is your feature request related to a problem? Please describe.**
I have a hacked ps2 with freemcboot.  I'm interested in writing some homebrew to use the ps2 network and ps2 controller to use it as a game pad.

**Describe the solution you'd like**
Before I build the developer tools I want to know if this is even possible or the write tool to build such a project.

**Describe alternatives you've considered**
I couldn't find anything that supported a socket connection as a game pad.
I could look at more source code for android wifi controllers.  Those are the only thing I know that work.

**Comment by nefarius** [comment]
Please don't e-mail me **and** create an issue, I get notifications about GH issues and will respond when there's time 🙄 

As per my mail response; this is not really a feature request for ViGEm but an entire project. Check the Contributing section in the README, there's links to likeminded folks, cheers.
