### ISSUE TITLE
PARSEC ViGEmBus issues

### ISSUE THREAD

**Issue by Wanaco21** [ViGEm/ViGEmBus#59]
Hi! My friend install Parsec to play online but it doesn't allow me to use my gamepad (the game pad is okay, it works in my computer). I asked in a Parsec forum and they told me to reinstall Parsec and install ViGEmBus manually. 
My friend did all of that but it still doesnt work (VigemBus doesn't appears in the devices manager)

**Comment by nefarius** [comment]
Hello,

on what OS version and driver version?

**Comment by Wanaco21** [comment]
Hi! Windows 10 64 bits, i really dont know too much about drivers and all that stuff. The main issue is that i installed Parsec (that should also contain the VigemBus driver but it didnt installed it) and i tried installing that Driver manually from a setup that the Parsec support guy sent me and it didnt worked. 
Windows 10 64 bits 10.0.19041.1

**Comment by nefarius** [comment]
I see, is something happening when the setup from here (the Release page) is used? Or does it just finish successfully and still nothing works in Parsec?

Cheers

**Comment by Wanaco21** [comment]
It just finish successfully and still nothing works in Parsec :(

**Comment by nefarius** [comment]
Ah I see, can you throw the following file my way from the machine that hosts: `c:\Windows\inf\setupapi.dev.log`

Thanks

**Comment by Wanaco21** [comment]
Should i upload that file here?

**Comment by DuckerMan** [comment]
dude just upload it on pastebin.com

**Comment by nefarius** [comment]
New setup has been released, please retry, if issue still relevant.
