### ISSUE TITLE
Xbox One controller emulation

### ISSUE THREAD

**Issue by FancyBanana** [ViGEm/ViGEmBus#62]
I would like to request addition of Xbox One controller emulation.

Dualsense, the new controller released by Sony for PS5 has adaptive trigger features that physically interact with fingers. It's possible to create many different effects like trigger pull resistance or _vibration_. With this new functionality it is possible to replicate the trigger vibration of the Xbox One controller. The is already an API for Dualsense but there is no known way to emulate Xbox One controller.

**Comment by Shayano** [comment]
Yes it's a great idea and it would allow to use the "copilot" function available on Windows 10 through the xbox accessories app.
It would simplify the life of solo games with multiple controllers.

**Comment by Myoko** [comment]
good idea!

**Comment by Masamune3210** [comment]
This might actually be better in something like DS4Windows

**Comment by FancyBanana** [comment]
Any updates on this issue?

**Comment by nefarius** [comment]
Nope.

**Comment by nefarius** [comment]
This is a topic for the successor.
