### ISSUE TITLE
Rumble events lasts too much time in 1.17.333

### ISSUE THREAD

**Issue by LuismaSP89** [ViGEm/ViGEmBus#66]
Using newer version of driver (1.17.333) "Tested with Cemu emulator" when a rumble event comes in, the rumble is extended too much time. For example, a rumble event that originally is only a hit or a shoot "0,25 seconds" the controller rumbles for 3-4 seconds. This is a bit annoying in games with too much rumble events.

Previously I used 1.6 version with some issues like controller disconnected problems when the rumble event come in. In this case, this is now solved, but this problem replaced the old one.

Using PS4 Dualshock V2.
Windows 10 x64 H2 Build.

**Comment by nefarius** [comment]
I don't know Cemu very much, is it using the client SDK or are you using some other software to feed the virtual controller?

**Comment by LuismaSP89** [comment]
Hello, I'm using the vigem driver + ds4 windows. But this problem started when I installed the latest version of vigem.

**Comment by nefarius** [comment]
Which exact fork and version of DS4Windows? Info, info, info!

**Comment by LuismaSP89** [comment]
Sorry. I'm using the latest version. You can download it from here:

https://github.com/Ryochan7/DS4Windows/releases

I don't know what more info can you need, but in case there's something more, please tell me.

And thanks for your help! : )

**Comment by nefarius** [comment]
I see, I shall investigate! I tested the release with Dolphin Emulator and there it behaved superb. I'm confident we get this resolved!

**Comment by LuismaSP89** [comment]
Hello again,
I figured you can test this not only in cemu emulator, it happens also with the proper ds4 windows itself.

Inside ds4 windows, go to profiles and edit the current profile "or create a new one if you don't have it" then, in the right side, go to "other" and select "test heavy" or "test light"  to test the rumble. When you stop the test, it keeps the rumble for 3-4 seconds more. So, is not a cemu only problem. Must be something in the latest vigem.

**Comment by LuismaSP89** [comment]
![57C66F65-E6AD-4FDB-8B8E-10CE8E12FA99](https://user-images.githubusercontent.com/12205048/103175126-fab61380-4867-11eb-98fa-2f759b36f4b8.jpeg)

**Comment by Ryochan7** [comment]
@LuismaSP89 That test is **completely independent** of ViGEmBus. More info would be needed as to what version of DS4Windows and which controller you are using.

All I can gleam from the screenshot is that it looks like you are using a pure black (0, 0, 0) lightbar color. People posted recently about a Force Feedback bug that only occurred when using pure black as the lightbar color. That issue was fixed in the latest release of DS4Windows (2.1.23).

**Comment by LuismaSP89** [comment]
I already posted the info. I'm using the latest version of ds4windows "2.1.23" and a ps4 dualshock V2.

In this case, I tested it and it doesn't matter about the lightbar color. The ds4 windows requires vigem driver, so, that's the reason to put the bug here. With older versions of vigem, this doesn't happen.

**Comment by nefarius** [comment]
Thanks for chiming in and the explanation, after the holidays I'll test the release as well. Currently I only own a first generation DS4 though if that's important.

**Comment by LuismaSP89** [comment]
In this case I think the generation of the DS4 makes no difference, the V2 has minor changes in the battery, sticks, and other optimizations in the bluetooth, but in my case, I use the controller wired, so, it doesn't matter.

**Comment by LuismaSP89** [comment]
Ok... I deleted the profile of DS4 Windows, created it again, set the lightbar other than 0,0,0, and now is working. Was not working before when I changed the lightbar.

My apologies man, sorry for wasted time. Closing.

**Comment by nefarius** [comment]
Whew, am glad mate, thought I made it worse with the update while it should make it rock-solid 😅 Game on!
