### ISSUE TITLE
v1.17.333: Windows 10 only 😭 ?

### ISSUE THREAD

**Issue by Darthagnon** [ViGEm/ViGEmBus#67]
Wish Win7 installation was still permitted. Guessing that it's because of low-level black magic, and not about signing a driver (or installing an unsigned one).

I'm holding off on updating drivers for the moment due to #65

**Comment by nefarius** [comment]
I am using Microsoft dependencies not available on anything lower than 10 now, sorry mate. One guy alone can't stomach that project without some outside help and MS puts and end to 7 and 8.x soon so I'll go with the flow.

**Comment by nefarius** [comment]
> I'm holding off on updating drivers for the moment due to #65

Well, without feedback and help from people suffering from this issue I can't fix it. Not able to replicate on any of my system so we gotta wait.

**Comment by Darthagnon** [comment]
Perfectly understandable; wishing you a happy new year!

**Comment by nefarius** [comment]
Likewise 😁 stay safe and healthy, cya in 2021!
