### ISSUE TITLE
will it support on win server 2019?

### ISSUE THREAD

**Issue by crazyevent** [ViGEm/ViGEmBus#69]
**Please don't abuse the issue tracker as a helpdesk!** We have a Discord server (linked in the README) where you can ask the lovely like-minded folks for assistance. Thank you for your compliance :smiley:

**Comment by nefarius** [comment]
Thanks for ignoring the issue template 🙄 

As it's the same kernel as the Windows 10 client builds, yes, it is supported, will update the README accordingly.
