### ISSUE TITLE
Will you consider adding the creation of a virtual keyboard and mouse? 

### ISSUE THREAD

**Issue by lVentus** [ViGEm/ViGEmBus#72]
Will you consider adding the creation of a virtual keyboard and mouse? 
Many games do not support controllers. I hope to make a software for mapping the mouse and keyboard to the controller.

**Comment by kittuov** [comment]
I'm trying to build an open source p2p Gamestreaming platform. I'm using ViGEm to handle "direct gamepads" and "Mobile touch screen -> gamepad" emulation.  keyboard and mouse are currently handled through windows builtin api which causes few issues with scrolling. 

if it's possible to add support for other devices like touchscreens etc, It'd be Fantastic.

**Comment by nefarius** [comment]
This is a topic for the successor.
