### ISSUE TITLE
Assertion failed: Could not find 'git' via 'C:\Windows\System32\where.exe'

### ISSUE THREAD

**Issue by EdwardElric64** [ViGEm/ViGEmBus#73]
Whenever I attempt to compile the driver powershell spits out the error "Assertion failed: Could not find 'git' via 'C:\Windows\System32\where.exe'" I installed everything asked of me in the pre requisite tab and restarded my PC to no avail. Why am I getting this error?

**Comment by nefarius** [comment]
How do you compile it? The PowerShell scripts are meant to run on CI so I have no idea if they even work locally.

**Comment by EdwardElric64** [comment]
In powershell I use the command that is on the page, ".\build.ps1 -configuration release"

**Comment by nefarius** [comment]
Works a treat over here, mate. Make sure your build environment has all the dependencies. Or build within Visual Studio.

![image](https://user-images.githubusercontent.com/286631/104134790-17843800-538c-11eb-991f-c53c917ec4af.png)
