### ISSUE TITLE
Would like to use a hotkey to unlock the mouse cursor, or have it unlock when I Alt + Tab to another window.

### ISSUE THREAD

**Issue by idgas01** [ViGEm/ViGEmBus#77]
Hi.  I am using the DualShock4 Emulator, which requires ViGEmBus.  It works well.  It makes it so that I can play games on PlayStation Now using a keyboard and mouse.  There is one thing though.  It locks the mouse cursor into the center of the screen.  I can understand the reasoning behind this.  It's probably to keep the mouse cursor from leaving the game window.  To prevent it from clicking items on the taskbar or maybe desktop shortcuts.  However, sometimes I want to Alt + Tab out of the PlayStation Now window and do something in another window.  I can Alt + Tab just fine, but my mouse cursor will still be locked in the center of the screen and I can't move it to do anything.  The only way to unlock the mouse cursor is to press the ~ key, which then closes the DS4Emulator program.  I have to completely close it before I can use my mouse again.  And then because I only need to do something in another window for a short period of time, when I Alt + Tab back to the PlayStation Now window it is inconvenient that I have to start the DS4Emulator again.  So what I'd like to be able to do is have a hotkey for unlocking and locking the mouse.  That way when I'm playing a game, I can Alt + Tab to another window, press the hotkey to unlock the mouse, do what needs to be done, press the hotkey to lock the mouse again, and then Alt + Tab back to the PlayStation Now window.  I don't know which program is responsible for locking the mouse cursor, so I thought that I would ask for help from both GitHubs - DualShock4 Emualtor and ViGEmBus.  Thank you for taking my situation under serious consideration.

**Comment by nefarius** [comment]
ViGEmBus emulation does nothing with your mouse, the behaviour you experience comes from other logic in the software you use.
