### ISSUE TITLE
Bluescreen due to ScpToolkit

### ISSUE THREAD

**Issue by Black-Moose** [ViGEm/ViGEmBus#78]
When i try to play with some friends via parsec i use my PS4 controller wich uses 360 emulation via the scp toolkit. But when playing my computer bluscreeens and says 
Stop code: SYSTEM SERVICE EXEPTION
What failed: ViGEmBus.sys

**Comment by nefarius** [comment]
ViGEmBus and ScpToolkit are not compatible; you can not run both on the same machine, [please thoroughly remove SCP](https://vigem.org/projects/ScpToolkit/ScpToolkit-Removal-Guide/) and you'll be fine.
