### ISSUE TITLE
the driver is unavailable

### ISSUE THREAD

**Issue by huseyinalperenn** [ViGEm/ViGEmBus#84]
![image](https://user-images.githubusercontent.com/34552292/109692187-47380b00-7b99-11eb-9926-a7f9f399c1ed.png)

**Comment by nefarius** [comment]
Good one, literally no helpful context provided whatsoever, easy fix 🙄

**Comment by Ryochan7** [comment]
Have you tried turning it off and on again?

**Comment by sergserg2** [comment]
I notice something similar. I'm using DS4 Windows. I think everything works fine when I start it for the first time. But if I restart (turn off/on connection in DS4 Windows) it locks up after a long while. Then the device cannot be turned off or removed. All that remains is to restart Windows.
This changed in last version of ViGEm, when fresh started after Windows boot is stable. Problem is later after reconnection. In earlier version this happens also on fresh started, but after long time (few hours).
 
![obraz](https://user-images.githubusercontent.com/31377653/109856863-46b37900-7c5a-11eb-80c3-c59981622014.png)

**Comment by nefarius** [comment]
Thanks @sergserg2 when that happens could you select the troubled device, then switch to View / Devices by connection and share that along with the error code in the General tab.

Cheers
