### ISSUE TITLE
Driver not working on Windows Server 2019

### ISSUE THREAD

**Issue by benjaminburkhardt** [ViGEm/ViGEmBus#85]
**Description**
I installed the latest version (ViGEmBus Setup 1.17.333) on a new Windows Server 2019 instance on AWS EC2.
Installation was successful and driver is visible in Device Manager. Unfortunately I cannot communication with the driver using the .NET API. The following error appears when connecting:
**System.ComponentModel.Win32Exception: 'The operation completed successfully'**
My program is working perfectly on my local Windows 10 machine with the same driver...

**To Reproduce**
1. Get new EC2 instance with Windows Server 2019
2. Install driver
3. try to .Connect() a new instance using .NET API.

**Screenshots**
![image](https://user-images.githubusercontent.com/18308827/111367149-b8e18000-8694-11eb-955b-f20b415fcfda.png)

**System details (please complete the following information):**
 - OS: Windows Server 2019
 - Feeder software: https://github.com/ViGEm/ViGEm.NET
 - Driver Version: 1.17.333

**Additional info**
I also tried to install the previous release (ViGEmBus Setup 1.16.116). With this version, the program runs without errors, BUT the commands do not come through...

**Comment by nefarius** [comment]
Server 2019 lacks the mandatory Xbox 360 drivers, have you installed them? Is the bus driver even present in Device Manager? Call stack?

**Comment by benjaminburkhardt** [comment]
I just tried to install the Xbox 360 drivers from, here (https://www.techspot.com/drivers/driver/file/information/17648/) but this did not help. Is there another driver that I could try?

In the Device Manager I can see that the **Nefarius Virtual Gamepad Emulation Bus** is installed. And as long as my Visual Studio Application is not stopped and stuck at the .Connect() command the "Other Device" **Virtual Xbox 360 Controller** gets visible. Maybe that helps?
![image](https://user-images.githubusercontent.com/18308827/111389419-3d41fc00-86b1-11eb-83f1-c5e4738e4d32.png)



The Call Stack is not very helpful: 
![image](https://user-images.githubusercontent.com/18308827/111388973-7fb70900-86b0-11eb-9d80-2ee646a37116.png)

Thanks a lot for your help!

**Comment by nefarius** [comment]
Yeah, as I said, Xbox 360 Driver is missing so the virtual controller can't boot and therefore nothing will work as expected.

Please don't just randomly copy parts of drivers around like that, it's a brilliant way to test if you have a good backup 🙂

[Use the archived copy of the X360 driver instead](http://web.archive.org/web/20200425215425/http://download.microsoft.com/download/6/9/4/69446ACF-E625-4CCF-8F56-58B589934CD3/Xbox360_64Eng.exe).

**Comment by benjaminburkhardt** [comment]
Great this was the missing piece! 😉 
Thank you!
