### ISSUE TITLE
Controller limit in Parsec 

### ISSUE THREAD

**Issue by Haunt334** [ViGEm/ViGEmBus#95]
When I host, my friends go online and test if their controllers work but the fifth controller doesn't work. Is there a limit of controllers that can be connected?

**Comment by nefarius** [comment]
Xbox/XInput/xusb22 has a historic hard-limit of **4 controllers**, there unfortunately isn't a way around it.

**Comment by nefarius** [comment]
[Closed since neither bug report nor feature request](https://vigem.org/Community-Support/).
