### ISSUE TITLE
Setup Wizard ended Prematurely 

### ISSUE THREAD

**Issue by yuripeters** [ViGEm/ViGEmBus#96]
![image](https://user-images.githubusercontent.com/82726319/115122750-2b3ccd00-9f7f-11eb-97f0-005233bc183e.jpg)

Hello, how do I fix this?

**Comment by lkru** [comment]
If you are running on Apple M1 chip through Parallels with ARM version of Windows then there is no solution so far.
I dug the whole night on how to solve it the other day. No solutions yet. 
This SW is designedfor Win 32 and 64 bit versions only.

If you prove me wrong I would be so glad!

**Comment by yuripeters** [comment]
But I use windows, Win 64 bit

**Comment by nefarius** [comment]
[Thanks for ignoring everything that could've been even remotely necessary to help you](https://vigem.org/Community-Support/).
