### ISSUE TITLE
Mac support ?

### ISSUE THREAD

**Issue by vemito1** [ViGEm/ViGEmBus#98]
Hey! 

I know this is currently only a windows 10 feature but I was wondering if your software will ever come to macOS! I’m hoping that it does!

**Comment by nefarius** [comment]
Hello,

I personally am miles away from the knowledge required about development in an Apple environment, their driver ecosystem and have never owned any Apple hardware. So the signs are not the best 😅 but I wonder what benefit would it bring, Virtual Xbox Controllers on MacOS I assume?

**Comment by vemito1** [comment]
Oh ok! It’s all good I know not many people dude software type of stuff on Mac thus it being limited to things that windows has that macOS doesn’t! 

Either way I really love this software and I can’t ware to see future inventions of yours

**Comment by pixluser** [comment]
> 

It'll permit to a software like dualsensex to work on mac, and to bring support DualSense with Adaptative triggers… also with an universal method for developpers on Steam working on several Os I guess.

If a mac dev want to bring vigem on mac that'll be nice so :D
